---
- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
  when: common_apt_update

- name: Install Common Packages
  ansible.builtin.apt:
    name: "{{ common_apt_packages }}"
    state: present
